name: Release
on:
  push:
    branches:
      - '*'

jobs:
  release-maven-central:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATEKEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: maven-central-release
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          create_tag: true

      - name: Release to Maven repo
        run: |
          mvn -P release -Dgpg.keyname=${{ secrets.GPG_KEYNAME }} -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
              -Drevision=${{ steps.calculate-version.outputs.version-string }} deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
